//! Alpha golden-vector corpus for generic packets, transforms, and keyed
//! placement (QUA-003 partial; roadmap v0.7.0 "Freeze immutable packet and
//! placement vectors").
//!
//! # STATUS: stable (owner-approved 2026-09-21)
//!
//! Every vector here is **generated deterministically by the test itself**
//! from fixed, documented seeds, keys, packet identifiers, and nonce
//! derivations — see the "Derivation" doc comment on each vector builder and
//! `testdata/packets/manifest.json`. The assertions check *internal
//! invariants* (deterministic encode, decode round-trip, known locator and
//! envelope prefixes, flag⇔transform coupling, keyed-carrier stealth) rather
//! than frozen bytes, so the suite passes before any byte fixture exists.
//!
//! Byte-level frozen fixtures are materialized by the owner in one command:
//!
//! cargo test -p steganographer-core --test golden_vectors -- --ignored
//! ```
//!
//! That run writes `<vector>.hex` files (plus `<vector>.hex.sha256` sidecars)
//! under `testdata/packets/`. Once frozen, every regular run (including CI,
//! via [`frozen_fixtures_match_when_present`]) compares regenerated bytes
//! against the frozen fixtures and fails on drift, per spec 05
//! ("schema and golden-vector immutability", "corpus manifest/hash validation").

use std::path::PathBuf;

use chacha20poly1305::{
    aead::{Aead, KeyInit, Payload},
    ChaCha20Poly1305, Nonce,
};
use ed25519_dalek::SigningKey;
use sha2::{Digest as _, Sha256};

use steganographer_core::carrier::{
    CarrierEmbedder, CarrierError, CarrierExtractor, EmbeddingConfig, KeyedInterleavedSpatialLsb,
    KeyedSpatialLsb, SpatialLsb,
};
use steganographer_core::encryption::{self, EncryptionKey};
use steganographer_core::kdf::derive_placement_key;
use steganographer_core::packet::{
    crc32c, AlgorithmDescriptor, DecodeLimits, GenericPacket, Locator, PacketEnvelope, PayloadKind,
    TransformDescriptor, FLAG_COMPRESSED, FLAG_ENCRYPTED, FLAG_KEYED_LOCATOR, FLAG_PAYLOAD_SIGNED,
    KERNEL_SPATIAL_LSB, LOCATOR_SIZE, PACKET_MAGIC, PLACEMENT_KEYED, PLACEMENT_SEQUENTIAL,
    PROTOCOL_MAJOR, PROTOCOL_MINOR,
};
use steganographer_core::placement::{
    InterleavedSchedule, KeyedPermutation, PLACEMENT_INTERLEAVED,
};
use steganographer_core::transforms::{
    self, TransformContext, DEFAULT_ECC_CHUNK_LEN, TRANSFORM_AEAD_CHACHA20_POLY1305,
    TRANSFORM_COMPRESS_DEFLATE, TRANSFORM_PAYLOAD_SIGN_ED25519,
};

// ---------------------------------------------------------------------------
// Fixed, documented inputs (test keys — not secrets; see manifest.json)
// ---------------------------------------------------------------------------

/// ChaCha20-Poly1305 payload key: `0x77` repeated 32 times.
const ENCRYPTION_TEST_KEY: [u8; 32] = [0x77; 32];

/// Ed25519 seed for the payload-signing identity: `0x33` repeated 32 times.
const SIGNING_TEST_SEED: [u8; 32] = [0x33; 32];

/// Embedding key for the PLC-002 keyed-placement carrier: `0x2c` repeated 32
/// times. Locator/placement subkeys derive from it via `kdf`.
const KEYED_PLACEMENT_EMBEDDING_KEY: [u8; 32] = [0x2c; 32];

/// Embedding key for the PLC-001 keyed-interleaved carrier: `0x3d` repeated 32
/// times.
const KEYED_INTERLEAVED_EMBEDDING_KEY: [u8; 32] = [0x3d; 32];

/// The 4-byte AEAD salt the encrypted vector is pinned to. Production
/// `encryption::encrypt` draws this from `OsRng`; the golden vector fixes one
/// value and replicates the documented derivation
/// `nonce = BLAKE3(salt || packet_id)[..12]`.
const FIXED_AEAD_SALT: [u8; 4] = [0xa5, 0x5a, 0x5a, 0xa5];

/// Shared decode limits for every vector (protocol defaults).
const LIMITS: DecodeLimits = DecodeLimits {
    max_envelope_len: 16 * 1024,
    max_body_len: 16 * 1024 * 1024,
    max_packet_len: 16 * 1024 * 1024 + 16 * 1024 + LOCATOR_SIZE,
    max_field_len: 8 * 1024,
    max_fields: 128,
    max_transforms: 16,
    max_extensions: 64,
    max_filename_len: 255,
    max_mime_len: 127,
    max_original_len: 16 * 1024 * 1024,
    max_nesting_depth: 3,
    max_aggregate_nested_bytes: 64 * 1024 * 1024,
};

/// Synthetic byte-carrier size (units) for the placement vectors.
const CARRIER_UNITS: usize = 4096;

/// Canonical bootstrap units consumed by the keyed recognition tag at 1 bit
/// per unit (64-bit tag).
const TAG_UNITS: usize = 64;

// ---------------------------------------------------------------------------
// Deterministic derivation helpers
// ---------------------------------------------------------------------------

/// Derive `n` deterministic bytes via a BLAKE3 hash chain:
/// `block_0 = BLAKE3(label)`, `block_{i+1} = BLAKE3(block_i)`, concatenated
/// and truncated to `n` bytes.
fn derive_bytes(label: &[u8], n: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(n + 32);
    let mut current = blake3::hash(label);
    while out.len() < n {
        out.extend_from_slice(current.as_bytes());
        current = blake3::hash(current.as_bytes());
    }
    out.truncate(n);
    out
}

/// 16-byte packet identifier for a vector:
/// `BLAKE3(b"golden packet-id: " ++ name)[..16]`.
fn packet_id_for(name: &str) -> [u8; 16] {
    let mut label = b"golden packet-id: ".to_vec();
    label.extend_from_slice(name.as_bytes());
    let hash = blake3::hash(&label);
    let mut id = [0u8; 16];
    id.copy_from_slice(&hash.as_bytes()[..16]);
    id
}

/// 8-byte public locator nonce for a vector:
/// `BLAKE3(b"golden locator-nonce: " ++ name)[..8]`.
fn locator_nonce_for(name: &str) -> [u8; 8] {
    let mut label = b"golden locator-nonce: ".to_vec();
    label.extend_from_slice(name.as_bytes());
    let hash = blake3::hash(&label);
    let mut nonce = [0u8; 8];
    nonce.copy_from_slice(&hash.as_bytes()[..8]);
    nonce
}

/// Synthetic byte carrier: `derive_bytes(b"golden carrier: " ++ name, units)`.
fn synthetic_carrier(name: &str, units: usize) -> Vec<u8> {
    let mut label = b"golden carrier: ".to_vec();
    label.extend_from_slice(name.as_bytes());
    derive_bytes(&label, units)
}

/// The spatial-LSB kernel descriptor shared by every vector: algorithm 1
/// (`KERNEL_SPATIAL_LSB`), version 1, parameters `[1]` (1 bit per unit).
fn kernel_descriptor() -> AlgorithmDescriptor {
    AlgorithmDescriptor::new(KERNEL_SPATIAL_LSB, 1, vec![1])
}

/// Replicate `encryption::derive_nonce`: `BLAKE3(salt || packet_id)[..12]`.
fn derive_aead_nonce(salt: &[u8; 4], packet_id: &[u8; 16]) -> [u8; 12] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(salt);
    hasher.update(packet_id);
    let hash = hasher.finalize();
    let mut nonce = [0u8; 12];
    nonce.copy_from_slice(&hash.as_bytes()[..12]);
    nonce
}

/// The AEAD associated data used by `transforms.rs`: packet identity binding
/// (`packet_id || payload_kind u16 BE || original_len u64 BE`).
fn transform_aad(ctx: &TransformContext<'_>) -> Vec<u8> {
    let mut aad = Vec::with_capacity(26);
    aad.extend_from_slice(ctx.packet_id);
    aad.extend_from_slice(&ctx.payload_kind.to_be_bytes());
    aad.extend_from_slice(&ctx.original_len.to_be_bytes());
    aad
}

/// Assemble a transformed generic packet: an envelope whose digest covers the
/// *logical* payload plus the recorded transform descriptors, the encoded
/// (transformed) body, and a locator carrying the mirroring flag bits.
#[allow(clippy::too_many_arguments)] // test-vector builder mirrors the packet shape
fn transformed_packet(
    logical_payload: &[u8],
    packet_id: [u8; 16],
    payload_kind: PayloadKind,
    transforms: Vec<TransformDescriptor>,
    body: Vec<u8>,
    flags: u16,
    placement: AlgorithmDescriptor,
    locator_nonce: [u8; 8],
) -> GenericPacket {
    let mut envelope = PacketEnvelope::for_payload(
        packet_id,
        payload_kind,
        logical_payload,
        placement,
        kernel_descriptor(),
    );
    envelope.transforms = transforms;
    let envelope_bytes = envelope.encode(&LIMITS).expect("envelope encodes");
    let locator = Locator::new(
        flags,
        envelope_bytes.len(),
        body.len(),
        crc32c(&envelope_bytes),
        locator_nonce,
        &LIMITS,
    )
    .expect("locator fits limits");
    GenericPacket {
        locator,
        envelope,
        body,
    }
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

// ---------------------------------------------------------------------------
// Shared invariant assertions
// ---------------------------------------------------------------------------

/// Core invariants every vector must satisfy:
///
/// 1. encode is deterministic (encode twice → identical bytes);
/// 2. the locator prefix is exactly `STG3` + protocol `1.0`;
/// 3. encoded length matches the locator's own accounting;
/// 4. decode(encoded) == packet, and decode→encode is byte-exact;
/// 5. the envelope TLV stream opens with the canonical critical field ids;
/// 6. the BLAKE3 content digest verifies against the logical payload.
fn assert_packet_invariants(packet: &GenericPacket, logical_payload: &[u8]) {
    let encoded = packet.encode(&LIMITS).expect("packet encodes");
    let again = packet.encode(&LIMITS).expect("packet re-encodes");
    assert_eq!(
        encoded, again,
        "encode must be deterministic (twice-identical bytes)"
    );

    // Known-length locator prefix, hand-computable from the spec.
    assert_eq!(encoded[..4], PACKET_MAGIC, "locator magic must be STG3");
    assert_eq!(encoded[4], PROTOCOL_MAJOR);
    assert_eq!(encoded[5], PROTOCOL_MINOR);
    let envelope_len = packet.locator.envelope_len as usize;
    assert_eq!(
        encoded.len(),
        LOCATOR_SIZE + envelope_len + packet.body.len(),
        "encoded length must equal locator + envelope + body"
    );

    // Decode round-trip, and canonical re-encode must be byte-exact.
    let decoded = GenericPacket::decode(&encoded, &LIMITS).expect("packet decodes");
    assert_eq!(&decoded, packet, "decode(encode(x)) must equal x");
    let reencoded = decoded.encode(&LIMITS).expect("decoded packet re-encodes");
    assert_eq!(
        reencoded, encoded,
        "decode→encode must round-trip byte-exact"
    );

    // Canonical envelope opening, hand-computable: critical packet-id TLV
    // (wire id 0x8001, 16-byte value), then the packet identifier itself.
    assert_eq!(
        &encoded[LOCATOR_SIZE..LOCATOR_SIZE + 6],
        &[0x80, 0x01, 0x00, 0x00, 0x00, 0x10],
        "first envelope field must be the critical 16-byte packet-id TLV"
    );
    assert_eq!(
        &encoded[LOCATOR_SIZE + 6..LOCATOR_SIZE + 22],
        &packet.envelope.packet_id[..],
        "packet-id TLV value must be the packet identifier"
    );
    let ids = envelope_wire_ids(&encoded, envelope_len);
    assert_eq!(
        &ids[..4],
        &[0x8001, 0x8002, 0x8003, 0x8004],
        "envelope must open with packet-id, payload-kind, original-length, content-digest"
    );
    assert!(
        ids.contains(&0x8006),
        "placement descriptor must be present"
    );
    assert!(ids.contains(&0x8007), "kernel descriptor must be present");
    assert!(ids.contains(&0x8008), "created-version must be present");

    assert!(
        packet.envelope.content_digest.verify(logical_payload),
        "BLAKE3 content digest must verify against the logical payload"
    );
}

/// Walk the envelope TLV headers and return the raw wire field identifiers
/// (critical bit included). The walk must consume the envelope exactly.
fn envelope_wire_ids(packet_bytes: &[u8], envelope_len: usize) -> Vec<u16> {
    let mut ids = Vec::new();
    let mut cursor = LOCATOR_SIZE;
    let end = LOCATOR_SIZE + envelope_len;
    while cursor < end {
        assert!(cursor + 6 <= end, "TLV header runs past the envelope");
        let raw = u16::from_be_bytes([packet_bytes[cursor], packet_bytes[cursor + 1]]);
        let len = u32::from_be_bytes([
            packet_bytes[cursor + 2],
            packet_bytes[cursor + 3],
            packet_bytes[cursor + 4],
            packet_bytes[cursor + 5],
        ]) as usize;
        assert!(cursor + 6 + len <= end, "TLV value runs past the envelope");
        ids.push(raw);
        cursor += 6 + len;
    }
    assert_eq!(cursor, end, "TLV walk must consume the envelope exactly");
    ids
}

/// `FLAG_ENCRYPTED` / `FLAG_PAYLOAD_SIGNED` must mirror the AEAD / signature
/// transform descriptors exactly: zeroing the flags on a transformed packet
/// must fail closed on encode.
fn assert_flag_transform_coupling(packet: &GenericPacket) {
    let mut broken = packet.clone();
    broken.locator.flags = 0;
    assert!(
        broken.encode(&LIMITS).is_err(),
        "locator flags must not be detachable from recorded transforms"
    );
}

// ---------------------------------------------------------------------------
// Vector builders
// ---------------------------------------------------------------------------

/// (a) Untransformed sequential packet.
///
/// Derivation:
/// - payload = `derive_bytes(b"golden payload: vector-01", 64)`
/// - packet_id = `packet_id_for("vector-01")`, locator nonce likewise
/// - placement `(PLACEMENT_SEQUENTIAL=1, v1, no params)`,
///   kernel `(KERNEL_SPATIAL_LSB=1, v1, [1])`
/// - locator flags `0x0000`, body = payload verbatim
fn vector_01_untransformed_sequential() -> GenericPacket {
    let payload = derive_bytes(b"golden payload: vector-01", 64);
    GenericPacket::new_untransformed(
        payload,
        packet_id_for("vector-01"),
        locator_nonce_for("vector-01"),
        PayloadKind::Bytes,
        AlgorithmDescriptor::new(PLACEMENT_SEQUENTIAL, 1, Vec::new()),
        kernel_descriptor(),
        &LIMITS,
    )
    .expect("untransformed packet builds")
}

/// (b) AEAD-encrypted packet with a pinned salt.
///
/// Derivation:
/// - payload = `derive_bytes(b"golden payload: vector-02", 72)`
/// - packet_id / locator nonce derived from the vector name
/// - key = `EncryptionKey(0x77 × 32)` (documented test key)
/// - AEAD salt pinned to `a5 5a 5a a5`;
///   nonce = `BLAKE3(salt || packet_id)[..12]`
/// - AAD = `packet_id || payload_kind(u16 BE) || original_len(u64 BE)`
/// - body = `salt(4) || ChaCha20-Poly1305-Seal(key, nonce, payload, aad)`
/// - placement `(PLACEMENT_SEQUENTIAL=1, v1, no params)`, flags `0x0002`
///
/// The deterministic construction replicates `encryption::encrypt` with a
/// pinned salt and is cross-checked against the crate below.
fn vector_02_encrypted_aead() -> GenericPacket {
    let payload = derive_bytes(b"golden payload: vector-02", 72);
    let packet_id = packet_id_for("vector-02");
    let payload_kind = PayloadKind::Bytes;
    let ctx = TransformContext {
        packet_id: &packet_id,
        payload_kind: payload_kind as u16,
        original_len: payload.len() as u64,
    };
    let aad = transform_aad(&ctx);
    let key = EncryptionKey::from_bytes(&ENCRYPTION_TEST_KEY);

    let (descriptors, flags) = {
        let (_, descriptors, flags) = transforms::apply(
            &payload,
            &ctx,
            None,
            false,
            Some(&key),
            0,
            DEFAULT_ECC_CHUNK_LEN,
        )
        .expect("AEAD transform applies");
        assert_eq!(descriptors.len(), 1);
        assert_eq!(descriptors[0].algorithm, TRANSFORM_AEAD_CHACHA20_POLY1305);
        assert_eq!(descriptors[0].parameters, Vec::<u8>::new());
        assert_eq!(flags, FLAG_ENCRYPTED);
        (descriptors, flags)
    };

    // Deterministic body: pin the salt, seal with the documented nonce.
    let cipher = ChaCha20Poly1305::new_from_slice(&ENCRYPTION_TEST_KEY).expect("32-byte key");
    let nonce = derive_aead_nonce(&FIXED_AEAD_SALT, &packet_id);
    let mut body = FIXED_AEAD_SALT.to_vec();
    body.extend_from_slice(
        &cipher
            .encrypt(
                Nonce::from_slice(&nonce),
                Payload {
                    msg: &payload,
                    aad: &aad,
                },
            )
            .expect("AEAD seal succeeds"),
    );
    assert_eq!(body.len(), 4 + payload.len() + 16);

    // Cross-check 1: the crate's decrypt accepts the pinned-salt body and the
    // documented AAD, recovering the payload.
    assert_eq!(
        encryption::decrypt(&key, &packet_id, &body, Some(&aad)).expect("crate decrypts"),
        payload,
        "pinned-salt body must decrypt under the documented derivation"
    );
    // Cross-check 2: a fresh crate-side encryption (random salt) must derive
    // its nonce with the exact same formula — reconstruct and decrypt it.
    let fresh = encryption::encrypt(&key, &packet_id, &payload, Some(&aad))
        .expect("crate-side encryption works");
    let fresh_salt: [u8; 4] = fresh[..4].try_into().expect("salt slice");
    let fresh_nonce = derive_aead_nonce(&fresh_salt, &packet_id);
    let recovered = ChaCha20Poly1305::new_from_slice(&ENCRYPTION_TEST_KEY)
        .expect("32-byte key")
        .decrypt(
            Nonce::from_slice(&fresh_nonce),
            Payload {
                msg: &fresh[4..],
                aad: &aad,
            },
        )
        .expect("crate salt must reconstruct the nonce via BLAKE3(salt||packet_id)[..12]");
    assert_eq!(recovered, payload);

    transformed_packet(
        &payload,
        packet_id,
        payload_kind,
        descriptors,
        body,
        flags,
        AlgorithmDescriptor::new(PLACEMENT_SEQUENTIAL, 1, Vec::new()),
        locator_nonce_for("vector-02"),
    )
}

/// (c) Keyed placement (PLC-002) over a synthetic carrier.
///
/// Derivation:
/// - payload = `derive_bytes(b"golden payload: vector-03", 80)`
/// - packet_id / locator nonce derived from the vector name
/// - placement `(PLACEMENT_KEYED=2, v1, no params)`, kernel `(1, v1, [1])`
/// - locator flags `0x0008` (`FLAG_KEYED_LOCATOR`)
/// - carrier = `derive_bytes(b"golden carrier: vector-03", 4096)`
/// - embedding key `0x2c` × 32; 1 bit per unit; the 8-byte keyed recognition
///   tag occupies the first 64 canonical units and packet bits land at
///   `KeyedPermutation` positions over the remaining 4032 units.
fn vector_03_keyed_placement() -> (GenericPacket, Vec<u8>) {
    let payload = derive_bytes(b"golden payload: vector-03", 80);
    let packet = GenericPacket::new_untransformed(
        payload,
        packet_id_for("vector-03"),
        locator_nonce_for("vector-03"),
        PayloadKind::Bytes,
        AlgorithmDescriptor::new(PLACEMENT_KEYED, 1, Vec::new()),
        kernel_descriptor(),
        &LIMITS,
    )
    .expect("keyed packet builds");

    // The keyed locator flag is deliberately not inferable by the builder;
    // the caller sets it on the locator, mirroring the carrier contract
    // ("the caller sets FLAG_KEYED_LOCATOR and PLACEMENT_KEYED").
    let mut packet = packet;
    packet.locator.flags = FLAG_KEYED_LOCATOR;

    let config = EmbeddingConfig { bits_per_unit: 1 };
    let packet_bytes = packet.encode(&LIMITS).expect("packet encodes");
    let mut carrier = synthetic_carrier("vector-03", CARRIER_UNITS);
    let report = KeyedSpatialLsb::new(KEYED_PLACEMENT_EMBEDDING_KEY)
        .embed_packet(&mut carrier, &packet_bytes, &config)
        .expect("keyed embedding fits");
    assert_eq!(report.packet_bytes, packet_bytes.len());
    (packet, carrier)
}

/// (d) Keyed interleaved placement (PLC-001) over a synthetic carrier.
///
/// Derivation:
/// - payload = `derive_bytes(b"golden payload: vector-04", 96)`
/// - placement `(PLACEMENT_INTERLEAVED=3, v1, no params)`, kernel `(1, v1, [1])`
/// - locator flags `0x0008` (`FLAG_KEYED_LOCATOR`)
/// - carrier = `derive_bytes(b"golden carrier: vector-04", 4096)`
/// - embedding key `0x3d` × 32; 1 bit per unit; body spread with the
///   coprime-stride `InterleavedSchedule` over the remaining 4032 units.
fn vector_04_keyed_interleaved() -> (GenericPacket, Vec<u8>) {
    let payload = derive_bytes(b"golden payload: vector-04", 96);
    let packet = GenericPacket::new_untransformed(
        payload,
        packet_id_for("vector-04"),
        locator_nonce_for("vector-04"),
        PayloadKind::Bytes,
        AlgorithmDescriptor::new(PLACEMENT_INTERLEAVED, 1, Vec::new()),
        kernel_descriptor(),
        &LIMITS,
    )
    .expect("interleaved packet builds");

    // Same explicit FLAG_KEYED_LOCATOR contract as the PLC-002 keyed vector.
    let mut packet = packet;
    packet.locator.flags = FLAG_KEYED_LOCATOR;

    let config = EmbeddingConfig { bits_per_unit: 1 };
    let packet_bytes = packet.encode(&LIMITS).expect("packet encodes");
    let mut carrier = synthetic_carrier("vector-04", CARRIER_UNITS);
    let report = KeyedInterleavedSpatialLsb::new(KEYED_INTERLEAVED_EMBEDDING_KEY)
        .embed_packet(&mut carrier, &packet_bytes, &config)
        .expect("interleaved embedding fits");
    assert_eq!(report.packet_bytes, packet_bytes.len());
    (packet, carrier)
}

/// (e) DEFLATE compression + Ed25519 payload signature (sign → compress order).
///
/// Derivation:
/// - payload = `b"alpha-provisional golden vector; "` × 6 = 198 bytes
/// - packet_id / locator nonce derived from the vector name
/// - signing seed = `0x33` × 32 (Ed25519, documented test key)
/// - `transforms::apply(sign, compress)`: sign the logical payload first, then
///   DEFLATE-compress (recorded only because it shrinks)
/// - flags `0x0011` (`FLAG_PAYLOAD_SIGNED | FLAG_COMPRESSED`), body = deflate
///   stream; placement `(PLACEMENT_SEQUENTIAL=1, v1, no params)`
fn vector_05_deflate_sign() -> GenericPacket {
    const UNIT: &[u8] = b"alpha-provisional golden vector; ";
    let payload: Vec<u8> = UNIT.iter().cycle().take(198).copied().collect();
    let packet_id = packet_id_for("vector-05");
    let payload_kind = PayloadKind::Text;
    let ctx = TransformContext {
        packet_id: &packet_id,
        payload_kind: payload_kind as u16,
        original_len: payload.len() as u64,
    };
    let signing_key = SigningKey::from_bytes(&SIGNING_TEST_SEED);

    let (body, descriptors, flags) = transforms::apply(
        &payload,
        &ctx,
        Some(&signing_key),
        true,
        None,
        0,
        DEFAULT_ECC_CHUNK_LEN,
    )
    .expect("sign+compress transforms apply");

    assert_eq!(flags, FLAG_PAYLOAD_SIGNED | FLAG_COMPRESSED);
    assert_eq!(descriptors.len(), 2);
    assert_eq!(
        descriptors[0].algorithm, TRANSFORM_PAYLOAD_SIGN_ED25519,
        "signing is applied first"
    );
    assert_eq!(
        descriptors[1].algorithm, TRANSFORM_COMPRESS_DEFLATE,
        "compression is applied second"
    );
    assert_eq!(descriptors[1].parameters, Vec::<u8>::new());
    assert!(
        body.len() < payload.len(),
        "DEFLATE must shrink the repeating payload"
    );

    transformed_packet(
        &payload,
        packet_id,
        payload_kind,
        descriptors,
        body,
        flags,
        AlgorithmDescriptor::new(PLACEMENT_SEQUENTIAL, 1, Vec::new()),
        locator_nonce_for("vector-05"),
    )
}

// ---------------------------------------------------------------------------
// Per-vector invariant tests
// ---------------------------------------------------------------------------

#[test]
fn vector_01_untransformed_sequential_invariants() {
    let packet = vector_01_untransformed_sequential();
    let payload = derive_bytes(b"golden payload: vector-01", 64);
    assert_packet_invariants(&packet, &payload);

    // Untransformed: body is the payload verbatim, no flags, no transforms.
    assert_eq!(packet.body, payload);
    assert_eq!(packet.locator.flags, 0);
    assert!(packet.envelope.transforms.is_empty());
    assert_eq!(
        packet.envelope.placement.algorithm, PLACEMENT_SEQUENTIAL,
        "vector declares sequential placement (1)"
    );

    // The same packet also embeds and extracts through the plain sequential
    // spatial-LSB carrier (descriptor 1, no keyed flag).
    let config = EmbeddingConfig { bits_per_unit: 1 };
    let packet_bytes = packet.encode(&LIMITS).expect("encodes");
    let mut carrier = synthetic_carrier("vector-01", CARRIER_UNITS);
    SpatialLsb
        .embed_packet(&mut carrier, &packet_bytes, &config)
        .expect("sequential embedding fits");
    let extracted = SpatialLsb
        .extract_packet(&carrier, &config, &LIMITS)
        .expect("sequential extraction succeeds");
    assert_eq!(extracted.packet, packet);
}

#[test]
fn vector_02_encrypted_aead_invariants() {
    let packet = vector_02_encrypted_aead();
    let payload = derive_bytes(b"golden payload: vector-02", 72);
    assert_packet_invariants(&packet, &payload);

    assert_eq!(packet.locator.flags, FLAG_ENCRYPTED);
    assert_eq!(
        packet.envelope.transforms[0].algorithm,
        TRANSFORM_AEAD_CHACHA20_POLY1305,
    );
    assert_eq!(
        packet.body[..4],
        FIXED_AEAD_SALT,
        "salt is pinned in the body"
    );
    assert_eq!(packet.body.len(), 4 + payload.len() + 16);

    // Full reverse recovers the payload under the documented key.
    let ctx = TransformContext {
        packet_id: &packet.envelope.packet_id,
        payload_kind: packet.envelope.payload_kind as u16,
        original_len: packet.envelope.original_len,
    };
    let key = EncryptionKey::from_bytes(&ENCRYPTION_TEST_KEY);
    let recovered = transforms::reverse(
        &packet.body,
        &ctx,
        Some(&key),
        &packet.envelope.transforms,
        packet.envelope.original_len,
    )
    .expect("decrypts with the documented key");
    assert_eq!(recovered, payload);
    assert!(packet.envelope.content_digest.verify(&recovered));

    // Wrong key fails closed (Poly1305 tag mismatch).
    let wrong = EncryptionKey::from_bytes(&[0x88; 32]);
    assert!(matches!(
        transforms::reverse(
            &packet.body,
            &ctx,
            Some(&wrong),
            &packet.envelope.transforms,
            packet.envelope.original_len,
        ),
        Err(transforms::TransformError::DecryptionFailed(_))
    ));

    // Flag⇔transform coupling: dropping FLAG_ENCRYPTED must fail encode.
    assert_flag_transform_coupling(&packet);
}

#[test]
fn vector_03_keyed_placement_carrier_invariants() {
    let (packet, carrier) = vector_03_keyed_placement();
    let payload = derive_bytes(b"golden payload: vector-03", 80);
    let packet_bytes = packet.encode(&LIMITS).expect("encodes");
    assert_packet_invariants(&packet, &payload);

    assert_eq!(packet.locator.flags, FLAG_KEYED_LOCATOR);
    assert_eq!(
        packet.envelope.placement.algorithm, PLACEMENT_KEYED,
        "vector declares keyed placement (2)"
    );

    // Deterministic embedding: re-embedding into a fresh copy of the clean
    // carrier is byte-identical, and a key-less scanner sees no STG3 magic.
    let config = EmbeddingConfig { bits_per_unit: 1 };
    let mut carrier_b = synthetic_carrier("vector-03", CARRIER_UNITS);
    let embedder = KeyedSpatialLsb::new(KEYED_PLACEMENT_EMBEDDING_KEY);
    embedder
        .embed_packet(&mut carrier_b, &packet_bytes, &config)
        .expect("re-embedding fits");
    assert_eq!(carrier, carrier_b, "keyed embedding is deterministic");
    assert_ne!(
        carrier[..4],
        PACKET_MAGIC,
        "keyed carrier must not expose the locator magic at the front"
    );

    // Round-trip extraction recovers the exact packet.
    let extracted = embedder
        .extract_packet(&carrier, &config, &LIMITS)
        .expect("extraction with the right key succeeds");
    assert_eq!(extracted.packet, packet);

    // A wrong key sees only "no packet".
    let wrong = KeyedSpatialLsb::new([0xee; 32]);
    assert!(matches!(
        wrong.extract_packet(&carrier, &config, &LIMITS),
        Err(CarrierError::NoPacket)
    ));

    // The Feistel schedule used over the body units is a true permutation.
    let body_units = CARRIER_UNITS - TAG_UNITS;
    let perm = KeyedPermutation::new(
        body_units,
        derive_placement_key(&KEYED_PLACEMENT_EMBEDDING_KEY),
        b"steganographer-placement-v1",
    );
    let mut seen = vec![false; body_units];
    for logical in 0..body_units {
        let physical = perm.permute(logical);
        assert!(physical < body_units, "permute stays in range");
        assert!(!seen[physical], "permute never collides");
        seen[physical] = true;
    }
}

#[test]
fn vector_04_keyed_interleaved_carrier_invariants() {
    let (packet, carrier) = vector_04_keyed_interleaved();
    let payload = derive_bytes(b"golden payload: vector-04", 96);
    let packet_bytes = packet.encode(&LIMITS).expect("encodes");
    assert_packet_invariants(&packet, &payload);

    assert_eq!(packet.locator.flags, FLAG_KEYED_LOCATOR);
    assert_eq!(
        packet.envelope.placement.algorithm, PLACEMENT_INTERLEAVED,
        "vector declares interleaved placement (3)"
    );

    let config = EmbeddingConfig { bits_per_unit: 1 };
    let mut carrier_b = synthetic_carrier("vector-04", CARRIER_UNITS);
    let embedder = KeyedInterleavedSpatialLsb::new(KEYED_INTERLEAVED_EMBEDDING_KEY);
    embedder
        .embed_packet(&mut carrier_b, &packet_bytes, &config)
        .expect("re-embedding fits");
    assert_eq!(carrier, carrier_b, "interleaved embedding is deterministic");
    assert_ne!(carrier[..4], PACKET_MAGIC, "keyed stealth at the front");

    let extracted = embedder
        .extract_packet(&carrier, &config, &LIMITS)
        .expect("extraction with the right key succeeds");
    assert_eq!(extracted.packet, packet);

    let wrong = KeyedInterleavedSpatialLsb::new([0xee; 32]);
    assert!(matches!(
        wrong.extract_packet(&carrier, &config, &LIMITS),
        Err(CarrierError::NoPacket)
    ));

    // The coprime-stride schedule over the body units is a bijection.
    let body_units = CARRIER_UNITS - TAG_UNITS;
    let schedule = InterleavedSchedule::new(
        body_units,
        derive_placement_key(&KEYED_INTERLEAVED_EMBEDDING_KEY),
        b"steganographer-placement-interleaved-v1",
    );
    let mut slots: Vec<usize> = (0..body_units).map(|i| schedule.slot(i)).collect();
    slots.sort_unstable();
    slots.dedup();
    assert_eq!(
        slots.len(),
        body_units,
        "schedule covers every slot exactly once"
    );
}

#[test]
fn vector_05_deflate_sign_invariants() {
    let packet = vector_05_deflate_sign();
    let payload: Vec<u8> = b"alpha-provisional golden vector; "
        .iter()
        .cycle()
        .take(198)
        .copied()
        .collect();
    assert_packet_invariants(&packet, &payload);

    assert_eq!(packet.locator.flags, FLAG_PAYLOAD_SIGNED | FLAG_COMPRESSED);
    assert_eq!(
        packet.envelope.transforms[0].algorithm,
        TRANSFORM_PAYLOAD_SIGN_ED25519,
    );
    assert_eq!(
        packet.envelope.transforms[1].algorithm,
        TRANSFORM_COMPRESS_DEFLATE,
    );
    // Sign-transform parameters are exactly public_key(32) || signature(64).
    assert_eq!(packet.envelope.transforms[0].parameters.len(), 96);
    assert!(packet.body.len() < payload.len());

    // Reverse decompresses and re-verifies the Ed25519 signature; no key
    // material is required on the decode side.
    let ctx = TransformContext {
        packet_id: &packet.envelope.packet_id,
        payload_kind: packet.envelope.payload_kind as u16,
        original_len: packet.envelope.original_len,
    };
    let recovered = transforms::reverse(
        &packet.body,
        &ctx,
        None,
        &packet.envelope.transforms,
        packet.envelope.original_len,
    )
    .expect("decompress + signature verify succeed");
    assert_eq!(recovered, payload);
    assert!(packet.envelope.content_digest.verify(&recovered));

    // Flag⇔transform coupling for both the sign and compression flags.
    assert_flag_transform_coupling(&packet);
}

// ---------------------------------------------------------------------------
// Frozen-fixture materialization and drift gate
// ---------------------------------------------------------------------------

/// Frozen artifact names and their exact expected bytes.
fn fixtures() -> Vec<(&'static str, Vec<u8>)> {
    let (packet_03, carrier_03) = vector_03_keyed_placement();
    let (packet_04, carrier_04) = vector_04_keyed_interleaved();
    vec![
        (
            "vector-01-untransformed-sequential",
            vector_01_untransformed_sequential()
                .encode(&LIMITS)
                .expect("encodes"),
        ),
        (
            "vector-02-encrypted-aead",
            vector_02_encrypted_aead().encode(&LIMITS).expect("encodes"),
        ),
        (
            "vector-03-keyed-placement-packet",
            packet_03.encode(&LIMITS).expect("encodes"),
        ),
        ("vector-03-keyed-placement-carrier", carrier_03),
        (
            "vector-04-keyed-interleaved-packet",
            packet_04.encode(&LIMITS).expect("encodes"),
        ),
        ("vector-04-keyed-interleaved-carrier", carrier_04),
        (
            "vector-05-deflate-sign",
            vector_05_deflate_sign().encode(&LIMITS).expect("encodes"),
        ),
    ]
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/packets")
}

fn fixture_path(name: &str, extension: &str) -> PathBuf {
    fixture_dir().join(format!("{name}.{extension}"))
}

/// Owner-facing one-command freeze: materializes every golden fixture that is
/// not yet frozen, and treats already-frozen files as an immutability gate
/// (regenerated bytes must match exactly, otherwise this test fails with a
/// drift report).
///
/// Run with:
///
/// ```text
/// cargo test -p steganographer-core --test golden_vectors -- --ignored
/// ```
#[test]
#[ignore = "materializes byte fixtures under testdata/packets/; run with -- --ignored"]
fn materialize_golden_fixtures() {
    let dir = fixture_dir();
    std::fs::create_dir_all(&dir).expect("testdata/packets is creatable");

    for (name, bytes) in fixtures() {
        let hex_text = format!("{}\n", to_hex(&bytes));

        let hex_path = fixture_path(name, "hex");
        if hex_path.exists() {
            let frozen = std::fs::read_to_string(&hex_path).expect("fixture readable");
            assert_eq!(
                frozen.trim(),
                hex_text.trim(),
                "golden vector drift for {name}: regenerated bytes differ from the frozen \
                 fixture. If this change is intentional, delete {name}.hex and re-run this \
                 test to re-freeze, then update manifest.json.",
            );
        } else {
            std::fs::write(&hex_path, &hex_text).expect("fixture file is writable");
            println!("froze {name}.hex ({} bytes)", bytes.len());
        }

        // SHA-256 sidecar so CI can gate fixture hashes without re-running Rust.
        let digest_hex = to_hex(&Sha256::digest(&bytes));
        let sidecar_text = format!("{digest_hex}  {name}.hex\n");
        let sidecar_path = fixture_path(name, "hex.sha256");
        if sidecar_path.exists() {
            let frozen = std::fs::read_to_string(&sidecar_path).expect("sidecar readable");
            assert_eq!(
                frozen.trim(),
                sidecar_text.trim(),
                "SHA-256 sidecar drift for {name}"
            );
        } else {
            std::fs::write(&sidecar_path, &sidecar_text).expect("sidecar file is writable");
        }
    }
}

/// Regular-run drift gate: when fixtures have been frozen by
/// [`materialize_golden_fixtures`], regenerated bytes must match them
/// byte-for-byte. Before the owner freezes fixtures, this passes vacuously.
#[test]
fn frozen_fixtures_match_when_present() {
    let dir = fixture_dir();
    let all = fixtures();
    let frozen: Vec<&(&str, Vec<u8>)> = all
        .iter()
        .filter(|(name, _)| dir.join(format!("{name}.hex")).exists())
        .collect();

    if frozen.is_empty() {
        eprintln!(
            "skipping: no frozen golden fixtures under testdata/packets yet; \
             run `cargo test -p steganographer-core --test golden_vectors -- --ignored` \
             to materialize them"
        );
        return;
    }

    for (name, bytes) in frozen {
        let frozen_hex =
            std::fs::read_to_string(dir.join(format!("{name}.hex"))).expect("fixture readable");
        assert_eq!(
            frozen_hex.trim(),
            to_hex(bytes),
            "golden vector drift for {name}"
        );
        let sidecar = std::fs::read_to_string(dir.join(format!("{name}.hex.sha256")))
            .expect("frozen sidecar readable");
        let digest_hex = to_hex(&Sha256::digest(bytes));
        assert_eq!(
            sidecar.trim(),
            format!("{digest_hex}  {name}.hex"),
            "SHA-256 sidecar drift for {name}"
        );
    }
}
